# Generated by Django 2.2.4 on 2019-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='Если это правда, то означает, что пользователь должен правильно проверить otp во втором API'),
        ),
    ]
